apiVersion: v1
kind: Service
metadata:
  name: sportsdev-service
spec:
  selector:
    app: sportsdev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30080