name: Build & Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: v1.0.21

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t kundan547/sportdev:${{ env.IMAGE_TAG }} .

    - name: Push Docker Image
      run: docker push kundan547/sportdev:${{ env.IMAGE_TAG }}

    - name: Update image tag in deployment.yaml
      run: |
        sed -i 's|kundan547/sportdev:.*|kundan547/sportdev:${{ env.IMAGE_TAG }}|' gitops/basic/deployment.yaml

    - name: Commit and Push updated deployment.yaml
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add gitops/basic/deployment.yaml
        git commit -m "Update image to ${{ env.IMAGE_TAG }}"
        git push origin master
